/**
 * The extension's Mandate vocabulary.
 *
 * 🚨 THIS FILE NO LONGER NAMES A MANDATE. Every key below comes from
 * `@ai-matrx/agents/mandates` (0.10.0), generated by THE ONE GENERATOR from
 * aidream's own `declared_mandates()`. The hand-typed literals that used to
 * live here were a mirror: a rename or a retirement on the server turned into
 * a 404 nobody saw, and the release report could not resolve this client's
 * references against the key set it actually shipped. A key that stops being
 * declared now fails TYPE-CHECK here.
 *
 * What this file still owns is the `mandate:` REF — the extension's own stable
 * UI identity for a Mandate-backed choice, stored in settings beside real agent
 * ids. That prefix is a client-side convention, not a platform key, so it is
 * adapted here and nowhere else.
 */

import { MANDATE_KEYS, type MandateKey } from '@ai-matrx/agents/mandates';

/** Canonical server-resolved target for a brand-new extension chat. */
export const DEFAULT_CHAT_MANDATE_KEY: MandateKey = MANDATE_KEYS.extend__browser_chat;

/**
 * Stable UI identity for a Mandate-backed choice. This is not an agent id and
 * is never sent to an agent-id route; the stream path uses `mandateKey`.
 */
export const DEFAULT_CHAT_MANDATE_REF = `mandate:${DEFAULT_CHAT_MANDATE_KEY}` as const;

export const STRUCTURED_EXTRACTOR_MANDATE_KEY: MandateKey =
  MANDATE_KEYS.extend__structured_extractor;
export const STRUCTURED_EXTRACTOR_MANDATE_REF =
  `mandate:${STRUCTURED_EXTRACTOR_MANDATE_KEY}` as const;

export const PATTERN_FROM_DATA_MANDATE_KEY: MandateKey = MANDATE_KEYS.extend__pattern_from_data;

export function isMandateAgentRef(value: string | null | undefined): boolean {
  return typeof value === 'string' && value.startsWith('mandate:');
}

/**
 * The key inside a `mandate:` ref, or `null` if it is not one.
 *
 * 🚨 This deliberately does NOT narrow to `MandateKey`. It decides which DOOR a
 * stored target goes through (`/v2/ai/mandates/{key}` vs the agent-id route),
 * and the SERVER — not this build's snapshot of the vocabulary — is the
 * authority on what exists. Narrowing here would send a ref naming a mandate
 * declared after this version shipped to the agent door, which fails in a way
 * that names the wrong thing. The vocabulary binds the keys we NAME (above);
 * this is a parse of a ref we stored.
 */
export function mandateKeyFromAgentRef(value: string | null | undefined): string | null {
  if (!isMandateAgentRef(value)) return null;
  const key = value?.slice('mandate:'.length) ?? '';
  return key.length > 0 ? key : null;
}
