import path from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'wxt';

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ['@wxt-dev/module-react'],
  srcDir: 'src',
  manifest: ({ mode }) => ({
    name: 'Matrx Extend',
    short_name: 'Matrx',
    description:
      'Agentic browser companion — chat, tasks, scraping, structured data extraction, and SEO.',
    // Dev-only stable extension ID: cihdmkcdjjckfhjpgoedmgfpoljebaml
    // Generated by: pnpm dlx node scripts/generate-extension-key.mjs
    // Private key lives at .secrets/matrx-extend.pem (gitignored).
    //
    // KEEP this line ENABLED for local unpacked installs and dev/CI
    // builds — without it, Chrome assigns a random ID and the OAuth
    // redirect (registered in Supabase as
    // https://cihdmkcdjjckfhjpgoedmgfpoljebaml.chromiumapp.org/) breaks
    // with "Authorization page could not be loaded".
    //
    // ⚠️ COMMENT THIS LINE OUT before running `pnpm zip` for ANY Web
    // Store upload — the dashboard rejects manifests whose `key` doesn't
    // match the keypair the Store assigned at first publish. The dev key
    // produces cihdmkcdjjckfhjpgoedmgfpoljebaml; the Store-assigned ID
    // for the published item is hnfolienncfklkgmdjjmhhegglimlamg, signed
    // with the Store's internal keypair. They never converge.
    //
    // After zipping for the Store, uncomment immediately so subsequent
    // dev installs keep the stable dev ID. Both IDs live in
    // src/config/identity.ts; both redirect URIs are in Supabase Auth.
    // Full incident: .research/v0.1.4-auth-incident.md.
    key: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1+MJD71hyTGZT40a/vRzeM9dz80VyHsiTm7zq8Yz0NxqVcl9nBx8GELq+FS0GUo1fUQBjqm17zPYtD/w4Y7TAzRY+AFu2wEzaP78b49gir3FEPw9liAhowraluj13Pg5tNPKTH1znL6rAsMi9VTrYm+WDJtj+nKI5CoKKKq0rQTUf/ChGn4Db1CrCnv7H33v9czYHZOBkksvni65uczSnDkx3x0+xH9ApJjiL5ADa2a9IUFwfBWML4AW+Q7jM7ZcegIBxsDtyzStgL7PR67cniI34An6Xsm+VVSyfP2uBP9eZr8FWfdehAmFo4v9WmxuVXAukJ+TuRAczbExT59FpQIDAQAB',
    permissions: [
      'storage',
      'sidePanel',
      'activeTab',
      'tabs',
      'tabGroups',
      'scripting',
      'identity',
      'offscreen',
      'nativeMessaging',
      'alarms',
      'contextMenus',
      'clipboardWrite',
      'downloads',
      'webNavigation',
      'history',
      'bookmarks',
      'notifications',
      'sessions',
      // Chrome forbids 'debugger' in optional_permissions. CDP client + network
      // capture need it; keeping it required is the only way to keep them working.
      'debugger',
    ],
    // Risky / privacy-sensitive permissions live here. Granted at runtime via
    // chrome.permissions.request from the admin "Advanced agent capabilities"
    // toggles in Settings.
    //
    // Only list permissions that are actually used in code — the Chrome Web
    // Store flags "declared but unused" optional permissions during review,
    // and any permission listed here also generates a Settings UI toggle via
    // src/lib/permissions/optional.ts. The two files MUST stay in sync.
    //
    // Reserved (re-enable here AND in src/lib/permissions/optional.ts when
    // wiring up the corresponding tools — see that file for the checklist):
    //   'userScripts', 'proxy', 'webRequest', 'desktopCapture', 'topSites',
    //   'management'
    optional_permissions: [
      'cookies',
      'pageCapture',
      'clipboardRead',
    ],
    host_permissions: [
      'https://server.app.matrxserver.com/*',
      'https://staging.server.app.matrxserver.com/*',
      'https://dev.server.app.matrxserver.com/*',
      'http://localhost:8000/*',
      'https://*.aimatrx.com/*',
      'https://txzxabzwovsujtloxrus.supabase.co/*',
      'http://127.0.0.1:22180/*',
      '<all_urls>',
    ],
    side_panel: {
      default_path: 'sidepanel.html',
    },
    action: {
      default_title: 'Matrx Extend',
      default_icon: {
        16: 'icon/16.png',
        32: 'icon/32.png',
        48: 'icon/48.png',
        128: 'icon/128.png',
      },
    },
    icons: {
      16: 'icon/16.png',
      32: 'icon/32.png',
      48: 'icon/48.png',
      128: 'icon/128.png',
    },
    web_accessible_resources: [
      {
        resources: ['data-picker.css', 'icon/*'],
        matches: ['<all_urls>'],
      },
    ],
    // Phase 2 C1.a — frontend bridge. The matrx-frontend admin app at
    // aimatrx.com (and per-PR Vercel previews / local dev) talks to this
    // extension via chrome.runtime.sendMessage(extId, …). The matches list
    // gates which page origins are allowed to deliver those messages.
    //
    // Keep in sync with src/lib/origin-allowlist.ts ALLOWED_ORIGIN_PATTERNS.
    // Both lists answer the same question ("can this origin talk to us?")
    // for two different transports (externally_connectable here, content
    // scripts / Broadcast handler in origin-allowlist).
    //
    // NOTE: Manifest V3 externally_connectable.matches REJECTS port wildcards
    // (`http://localhost:*/*`). Bare-host patterns implicitly match any port,
    // so `http://localhost/*` covers `http://localhost:3000/*`,
    // `http://localhost:3001/*`, etc.
    externally_connectable: {
      matches: [
        'https://*-armani-sadeghis-projects.vercel.app/*',
        'https://*.aimatrx.com/*',
        'https://*.mymatrx.com/*',
        'http://localhost/*',
        'http://127.0.0.1/*',
      ],
    },
    ...(mode === 'development'
      ? { content_security_policy: { extension_pages: "script-src 'self'; object-src 'self'" } }
      : {}),
  }),
  vite: () => ({
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
        '@gen': path.resolve(__dirname, './types/python-generated'),
      },
    },
    build: {
      sourcemap: true,
      // Default 500 kB is noisy for an extension: install is one-time, bundles
      // load from disk (no network cost), and the remaining oversized chunks
      // are all already correctly lazy-loaded.
      //   - AnnotationEditor (~1.6 MB) — tldraw, lazy via React.lazy in
      //     GuidancePreview, only when the user clicks Annotate.
      //   - cpp / wasm / lucide-react vendor chunks — split out by Vite,
      //     loaded on demand when a code block of that language renders.
      // Sidepanel-tab code is split via React.lazy in App.tsx (see
      // VIEW_LOADERS), so the eager sidepanel chunk stays small (~90 kB).
      chunkSizeWarningLimit: 1700,
    },
  }),
  outDir: '.output',
  imports: false,
});
