import path from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'wxt';

const devExtensionKey =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1+MJD71hyTGZT40a/vRzeM9dz80VyHsiTm7zq8Yz0NxqVcl9nBx8GELq+FS0GUo1fUQBjqm17zPYtD/w4Y7TAzRY+AFu2wEzaP78b49gir3FEPw9liAhowraluj13Pg5tNPKTH1znL6rAsMi9VTrYm+WDJtj+nKI5CoKKKq0rQTUf/ChGn4Db1CrCnv7H33v9czYHZOBkksvni65uczSnDkx3x0+xH9ApJjiL5ADa2a9IUFwfBWML4AW+Q7jM7ZcegIBxsDtyzStgL7PR67cniI34An6Xsm+VVSyfP2uBP9eZr8FWfdehAmFo4v9WmxuVXAukJ+TuRAczbExT59FpQIDAQAB';
const isChromeWebStoreBuild = process.env.MATRX_CWS_BUILD === '1';
const chromeWebStoreEntrypoints = [
  'background',
  'content',
  'data-picker',
  'diagnose-picker',
  'highlighter',
  'list-picker',
  'mic-grant',
  'offscreen',
  'options',
  'sidepanel',
  'webmcp-bridge',
];

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ['@wxt-dev/module-react'],
  srcDir: 'src',
  // Chrome's action click has exactly one job in the Store build: open the
  // side panel. WXT automatically turns any `popup` entrypoint into
  // action.default_popup, which takes precedence over the action click and
  // hides the reviewer-ready guest experience behind the legacy popup.
  ...(isChromeWebStoreBuild ? { filterEntrypoints: chromeWebStoreEntrypoints } : {}),
  manifest: ({ mode }) => ({
    name: 'Matrx Extend',
    short_name: 'Matrx',
    description: 'AI assistant for understanding and working with the page open in your browser.',
    // Dev-only stable extension ID: cihdmkcdjjckfhjpgoedmgfpoljebaml
    // Generated by: pnpm dlx node scripts/generate-extension-key.mjs
    // Private key lives at .secrets/matrx-extend.pem (gitignored).
    //
    // KEEP this line ENABLED for local unpacked installs and dev/CI
    // builds — without it, Chrome assigns a random ID and the OAuth
    // redirect (registered in Supabase as
    // https://cihdmkcdjjckfhjpgoedmgfpoljebaml.chromiumapp.org/) breaks
    // with "Authorization page could not be loaded".
    //
    // `pnpm zip:store` sets MATRX_CWS_BUILD=1 and omits this key. The
    // dashboard rejects manifests whose key does not match the keypair the
    // Store assigned at first publish. The dev key produces
    // cihdmkcdjjckfhjpgoedmgfpoljebaml; the Store-assigned ID for the
    // published item is hnfolienncfklkgmdjjmhhegglimlamg. They never
    // converge.
    //
    // Both IDs live in src/config/identity.ts; both redirect URIs are in
    // Supabase Auth. Full incident: .research/v0.1.4-auth-incident.md.
    ...(isChromeWebStoreBuild ? {} : { key: devExtensionKey }),
    permissions: [
      'storage',
      'sidePanel',
      'activeTab',
      'tabs',
      'tabGroups',
      'scripting',
      'identity',
      'offscreen',
      'nativeMessaging',
      'alarms',
      'contextMenus',
      'clipboardWrite',
      'downloads',
      'webNavigation',
      'history',
      'bookmarks',
      'notifications',
      'sessions',
      // Chrome forbids 'debugger' in optional_permissions. CDP client + network
      // capture need it; keeping it required is the only way to keep them working.
      'debugger',
      // REMOVED 2026-07-11 for the Chrome Web Store submission:
      //   system.cpu, system.memory, system.display,
      //   declarativeNetRequestWithHostAccess
      // These served ONLY two admin-gated diagnostic tools a reviewer can never
      // reach, so they read as "declared but unused" — a documented rejection
      // cause (same rule that flagged contextMenus on v0.1.4). The tools were
      // removed with them. To restore, see /Users/armanisadeghi/code/common-docs/systems/clients/extension/CHROME-WEB-STORE.md §2
      // — but every re-added permission MUST have a reviewer-reachable consumer
      // first. Do not re-add "preemptively"; that is exactly what got flagged.
    ],
    // Risky / privacy-sensitive permissions live here. Granted at runtime via
    // chrome.permissions.request from the admin "Advanced agent capabilities"
    // toggles in Settings.
    //
    // Only list permissions that are actually used in code — the Chrome Web
    // Store flags "declared but unused" optional permissions during review,
    // and any permission listed here also generates a Settings UI toggle via
    // src/lib/permissions/optional.ts. The two files MUST stay in sync.
    //
    // Reserved (re-enable here AND in src/lib/permissions/optional.ts when
    // wiring up the corresponding tools — see that file for the checklist):
    //   'userScripts', 'proxy', 'webRequest', 'desktopCapture', 'topSites',
    //   'management'
    optional_permissions: ['cookies', 'pageCapture', 'clipboardRead', 'tabCapture'],
    // Host permissions — broad web access at install time so the agent can
    // read / interact with arbitrary pages without the user fighting Chrome
    // dialogs every time. We previously experimented with moving <all_urls>
    // to optional_host_permissions (roadmap item #10) but the resulting UX
    // was unacceptable: every page-reading tool refused with a "go to
    // Settings" error message and the persistent content scripts (data
    // picker, list picker, content bridge) couldn't auto-inject. Reverted
    // 2026-05-08 — broad host access is back in base. The matrx server
    // tiers, the admin app, the matrx-local engine, and Supabase URLs are
    // already covered by <all_urls> but we keep them listed explicitly so
    // they stay obvious to anyone reading the manifest.
    host_permissions: [
      '<all_urls>',
      'https://server.app.matrxserver.com/*',
      'https://staging.server.app.matrxserver.com/*',
      'https://dev.server.app.matrxserver.com/*',
      'http://localhost:8000/*',
      'https://aimatrx.com/*',
      'https://*.aimatrx.com/*',
      'https://db.matrxserver.com/*',
      'http://127.0.0.1:22180/*',
    ],
    side_panel: {
      default_path: 'sidepanel.html',
    },
    action: {
      default_title: 'Matrx Extend',
      default_icon: {
        16: 'icon/16.png',
        32: 'icon/32.png',
        48: 'icon/48.png',
        128: 'icon/128.png',
      },
    },
    icons: {
      16: 'icon/16.png',
      32: 'icon/32.png',
      48: 'icon/48.png',
      128: 'icon/128.png',
    },
    web_accessible_resources: [
      {
        resources: ['data-picker.css', 'icon/*'],
        matches: ['<all_urls>'],
      },
    ],
    // Phase 2 C1.a — frontend bridge. The matrx-frontend admin app at
    // aimatrx.com (and per-PR Vercel previews / local dev) talks to this
    // extension via chrome.runtime.sendMessage(extId, …). The matches list
    // gates which page origins are allowed to deliver those messages.
    //
    // Mirrors src/lib/origin-allowlist.ts ALLOWED_ORIGIN_PATTERNS, but
    // intentionally LOOSER where Chrome's match-pattern grammar can't
    // express the runtime rule. Chrome rejects mid-host wildcards
    // (`*-armani-sadeghis-projects.vercel.app`) — only full-subdomain
    // wildcards (`*.vercel.app`) are legal. So the manifest opens the
    // gate to all `*.vercel.app` origins; the runtime matcher in
    // origin-allowlist.ts (which uses a custom regex) enforces the
    // narrower per-team restriction.
    //
    // NOTE: Manifest V3 externally_connectable.matches also REJECTS port
    // wildcards (`http://localhost:*/*`). Bare-host patterns implicitly
    // match any port, so `http://localhost/*` covers
    // `http://localhost:3000/*`, `http://localhost:3001/*`, etc.
    externally_connectable: {
      matches: [
        'https://*.vercel.app/*',
        'https://*.aimatrx.com/*',
        'https://*.mymatrx.com/*',
        'http://localhost/*',
        'http://127.0.0.1/*',
      ],
    },
    ...(mode === 'development'
      ? { content_security_policy: { extension_pages: "script-src 'self'; object-src 'self'" } }
      : {}),
  }),
  vite: () => ({
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
        '@gen': path.resolve(__dirname, './types/python-generated'),
      },
    },
    build: {
      sourcemap: true,
      // Default 500 kB is noisy for an extension: install is one-time, bundles
      // load from disk (no network cost), and the remaining oversized chunks
      // are all already correctly lazy-loaded.
      //   - AnnotationEditor (~1.6 MB) — tldraw, lazy via React.lazy in
      //     GuidancePreview, only when the user clicks Annotate.
      //   - cpp / wasm / lucide-react vendor chunks — split out by Vite,
      //     loaded on demand when a code block of that language renders.
      // Sidepanel-tab code is split via React.lazy in App.tsx (see
      // VIEW_LOADERS), so the eager sidepanel chunk stays small (~90 kB).
      chunkSizeWarningLimit: 1700,
    },
  }),
  // Dev server port. WXT defaults to 3000 (with fallbacks 3001-3010), which
  // collides with matrx-frontend's Next.js dev server. Pin to 3025 — clearly
  // off the beaten path and out of conflict with the sibling app.
  // `strictPort: true` is set automatically by WXT when a port is specified.
  dev: {
    server: {
      port: 3025,
    },
  },
  outDir: '.output',
  imports: false,
});
