/**
 * ─────────────────────────────────────────────────────────────────────────────
 * ⚠️ THIRD COPY OF A THREE-WAY MIRROR — do not re-derive, do not "improve".
 * ─────────────────────────────────────────────────────────────────────────────
 * The deterministic page-audit evaluators exist in three places, and all three
 * are byte-identical in logic, thresholds, AND issue strings:
 *
 *   1. CANONICAL Python — aidream
 *      `packages/matrx-scraper/matrx_scraper/audit_metrics.py`
 *   2. matrx-frontend — `features/marketing/seo/audit/`
 *   3. THIS DIRECTORY — matrx-extend `src/lib/seo/evaluators/`
 *
 * **All three change in the same unit of work.** A threshold or message
 * changed here alone silently makes the extension disagree with the crawler
 * and the web app about the same page, and every side persists its answer.
 * Parity is locked by `tests/unit/seo-evaluator-parity.test.ts`, which runs the
 * Python-generated fixture copied verbatim from matrx-frontend
 * (`__fixtures__/audit-parity.json`). Never regenerate that fixture here — it
 * is generated by the Python.
 *
 * WHY THE EXTENSION NEEDS ITS OWN COPY: the evaluators must run against the
 * LIVE DOM the user is looking at (post-JS, signed-in, localhost, offline),
 * which is exactly the reason `src/lib/seo/audit.ts` exists — read its header.
 * The evaluators are fed from `SeoAudit` by `from-audit.ts`, which is the only
 * file in this directory that is NOT a mirror.
 *
 * This file: shared shapes.
 * Persisted contract: `web.snapshot.audit_metrics` (v1) — see `stored.ts`.
 */

export type AuditSeverity = 'error' | 'warning';

export interface AuditIssue {
  severity: AuditSeverity;
  message: string;
}

/** True when no error-severity issues are present (warnings allowed). */
export function issuesOk(issues: AuditIssue[]): boolean {
  return issues.every((issue) => issue.severity !== 'error');
}
