/**
 * TS ↔ Python parity for the deterministic page-audit evaluators, third copy.
 *
 * The fixture (`__fixtures__/audit-parity.json`) is GENERATED by the canonical
 * Python (`aidream packages/matrx-scraper/matrx_scraper/audit_metrics.py`) and
 * was copied VERBATIM from matrx-frontend
 * (`features/marketing/seo/audit/__fixtures__/audit-parity.json`). Never
 * regenerate it here — the extension is a consumer of the contract, not its
 * author. If this fails, one of the three copies changed without the others;
 * fix ALL of them in the same unit of work and regenerate the fixture from the
 * Python.
 */

import { evaluateHeadingStructure, headingInputsFromRaw } from '@/lib/seo/evaluators/headings';
import { evaluateIndexability } from '@/lib/seo/evaluators/indexability';
import { evaluateSocialCard } from '@/lib/seo/evaluators/social';
import {
  headingsToStored,
  indexabilityToStored,
  socialInputFromRawTags,
  socialToStored,
  urlQualityToStored,
} from '@/lib/seo/evaluators/stored';
import { evaluateUrlQuality } from '@/lib/seo/evaluators/url-quality';
import { describe, expect, it } from 'vitest';
import parity from './__fixtures__/audit-parity.json';

interface SocialCase {
  input: { og: Record<string, unknown>; twitter: Record<string, unknown> };
  output: Record<string, unknown>;
}
interface HeadingsCase {
  input: unknown;
  output: Record<string, unknown>;
}
interface IndexabilityCase {
  input: {
    http_status: number | null;
    meta_robots: string | null;
    canonical_url: string | null;
    redirect_chain: { url: string; status: number | null }[];
    final_url: string | null;
  };
  output: Record<string, unknown>;
}
interface UrlQualityCase {
  input: string;
  output: Record<string, unknown>;
}

const fixture = parity as unknown as {
  social: SocialCase[];
  headings: HeadingsCase[];
  indexability: IndexabilityCase[];
  url_quality: UrlQualityCase[];
};

describe('page-audit TS ↔ Python parity', () => {
  it('fixtures are non-trivial', () => {
    expect(fixture.social.length).toBeGreaterThanOrEqual(5);
    expect(fixture.headings.length).toBeGreaterThanOrEqual(5);
    expect(fixture.indexability.length).toBeGreaterThanOrEqual(5);
    expect(fixture.url_quality.length).toBeGreaterThanOrEqual(5);
  });

  it.each(fixture.social.map((c, i) => [i, c] as const))(
    'social card case %d matches Python',
    (_i, testCase) => {
      const ts = socialToStored(
        evaluateSocialCard(socialInputFromRawTags(testCase.input.og, testCase.input.twitter)),
      );
      expect(ts).toEqual(testCase.output);
    },
  );

  it.each(fixture.headings.map((c, i) => [i, c] as const))(
    'heading structure case %d matches Python',
    (_i, testCase) => {
      const ts = headingsToStored(evaluateHeadingStructure(headingInputsFromRaw(testCase.input)));
      expect(ts).toEqual(testCase.output);
    },
  );

  it.each(fixture.url_quality.map((c, i) => [i, c] as const))(
    'url quality case %d matches Python',
    (_i, testCase) => {
      const ts = urlQualityToStored(evaluateUrlQuality(testCase.input));
      expect(ts).toEqual(testCase.output);
    },
  );

  it.each(fixture.indexability.map((c, i) => [i, c] as const))(
    'indexability case %d matches Python',
    (_i, testCase) => {
      const ts = indexabilityToStored(
        evaluateIndexability({
          httpStatus: testCase.input.http_status,
          metaRobots: testCase.input.meta_robots,
          canonicalUrl: testCase.input.canonical_url,
          redirectChain: testCase.input.redirect_chain,
          finalUrl: testCase.input.final_url,
        }),
      );
      expect(ts).toEqual(testCase.output);
    },
  );
});
