/**
 * MECHANICAL cross-language parity for the SEO audit.
 *
 * `tests/fixtures/seo-audit-parity.json` is GENERATED by the canonical Python
 * auditor (`aidream packages/matrx-scraper/matrx_scraper/seo_audit.py::audit_html`)
 * via `packages/matrx-scraper/scripts/generate_seo_audit_parity_fixture.py`.
 * This test replays the same HTML through `runAudit` and asserts the extension
 * produces the same numbers. If it fails, ONE SIDE CHANGED WITHOUT THE OTHER —
 * fix BOTH in the same unit of work and regenerate the fixture:
 *
 *   cd /Users/armanisadeghi/code/aidream
 *   .venv/bin/python packages/matrx-scraper/scripts/generate_seo_audit_parity_fixture.py
 *
 * Sibling test `seo-audit-parity.test.ts` pins the same RULES in hand-written
 * prose (why each one exists, which bug it caught). That one explains; this one
 * proves. Keep both.
 *
 * Same recipe as matrx-frontend's `features/marketing/seo/audit/audit.parity.test.ts`.
 */
import { runAudit, type SeoAudit } from '@/lib/seo/audit';
import { describe, expect, it } from 'vitest';
import fixture from '../fixtures/seo-audit-parity.json';

/** The flat server shape, restricted to the fields the extension also computes. */
interface ExpectedAudit {
  url: string;
  title: string;
  title_length: number;
  meta_description: string | null;
  meta_description_length: number;
  canonical: string | null;
  robots: string | null;
  lang: string | null;
  hreflang: { lang: string; href: string }[];
  og: Record<string, string>;
  twitter: Record<string, string>;
  schema_types: string[];
  headings: { level: number; text: string }[];
  internal_links: number;
  external_links: number;
  images_total: number;
  images_missing_alt: number;
  word_count: number;
  sentence_count: number;
  flesch_reading_ease: number | null;
}

interface ParityCase {
  name: string;
  why: string;
  base_url: string;
  html: string;
  expected: ExpectedAudit;
}

const cases = (fixture as { cases: ParityCase[] }).cases;

/**
 * Parse fixture HTML the way the production fetch-and-parse path sees it.
 *
 * `runAudit` reads `body.innerText` first and falls back to `textContent` —
 * correct in a live tab, where innerText is the RENDERED text. In Chrome, a
 * `DOMParser` document is never rendered, so `innerText` is `''` and the
 * fallback (which is what the server's parser also sees) takes over. happy-dom
 * is UNFAITHFUL here: it returns a non-empty innerText that concatenates inline
 * elements with no separator at all ("internal relinternal abs"), so the audit
 * would measure a string neither Chrome nor the server ever produces.
 *
 * Forcing `innerText` to `''` reproduces Chrome's DOMParser behaviour exactly.
 * This is emulating the environment, not weakening the assertion — the live-tab
 * innerText path is a deliberate divergence documented above and cannot be
 * fixture-compared at all.
 */
function parse(html: string): Document {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  if (doc.body) Object.defineProperty(doc.body, 'innerText', { value: '', configurable: true });
  return doc;
}

/**
 * The extension names fields for its own nested display shape; the server's are
 * flat. The mapping is 1:1 and is documented in the header of
 * `src/lib/seo/audit.ts` — this function IS that mapping, executed.
 */
function toServerShape(a: SeoAudit): ExpectedAudit {
  return {
    url: a.url,
    title: a.title.value,
    title_length: a.title.length,
    meta_description: a.description.value,
    meta_description_length: a.description.length,
    canonical: a.canonical,
    robots: a.robots,
    lang: a.lang,
    hreflang: a.hreflang,
    og: a.og,
    twitter: a.twitter,
    schema_types: a.schema_types,
    headings: a.headings,
    internal_links: a.links.internal,
    external_links: a.links.external,
    images_total: a.images.total,
    images_missing_alt: a.images.missing_alt,
    word_count: a.word_count,
    sentence_count: a.sentence_count,
    flesch_reading_ease: a.flesch_reading_ease,
  };
}

/**
 * Fields the extension computes but that are NOT compared, each skipped
 * EXPLICITLY (a quiet omission is how the last four divergences survived):
 *
 * - `fetched_at` — wall-clock at audit time. Not a server field at all.
 * - `performance` — `performance.getEntriesByType('navigation')`. Browser-only;
 *   the server has no navigation timing to mirror. Null in this environment.
 *
 * Server fields NOT compared because the extension deliberately does not
 * compute them (they need a crawl, not a tab — see the audit.ts header):
 * `schema_org`, `h1`/`h2`/`h1_count`, `link_count`, `links[]` (the link graph),
 * `text_hash`, `content_fingerprint`, `structured_data`, `image_inventory`,
 * `resources`, `page_identity`, `mixed_content`, `pagination`. The generator's
 * `compared_fields` list is the authority; this test asserts it hasn't grown
 * silently.
 *
 * STRUCTURAL LIMITS — these fields match here but CANNOT be guaranteed to match
 * against a live tab, and that is by design, not a bug to chase:
 *
 * - `word_count` / `sentence_count` / `flesch_reading_ease` derive from text.
 *   Against a live tab the extension reads `document.body.innerText` — the
 *   RENDERED text, which honours `display:none`, `visibility:hidden`, and CSS
 *   `::before`/`::after` content. The server reads the PARSED text of the HTML
 *   it fetched. On any page with hidden nav, tabs, or an unhydrated SPA shell
 *   the two legitimately differ; on an SPA the server may see nothing at all.
 *   That difference is the entire reason this second implementation exists.
 *   Here both sides read parsed text (DOMParser + the `textContent` fallback),
 *   so the COUNTING RULES are comparable — which is what this test pins.
 * - Text separators: selectolax's `text(separator=" ")` inserts a space between
 *   text nodes; DOM `textContent` does not. Fixture HTML puts real whitespace
 *   between block tags (as real HTML does) so both see the same word
 *   boundaries. Inline markup INSIDE a heading (`<h1>a <b>b</b></h1>`) is the
 *   one shape where the two genuinely disagree, so fixtures avoid it.
 * - `canonical` / `hreflang[].href`: the server returns the RAW `href`
 *   attribute; the DOM's `.href` property RESOLVES it against the document
 *   base. Fixtures use absolute hrefs, where the two agree. See the note in
 *   `src/lib/seo/audit.ts` — relative canonicals are a real, documented
 *   difference, not something this fixture papers over.
 */
const UNCOMPARED_BY_DESIGN = ['fetched_at', 'performance'] as const;

describe('seo audit — mechanical parity with the Python-generated fixture', () => {
  it('the fixture is real and covers the cases that drifted', () => {
    expect(cases.length).toBeGreaterThanOrEqual(12);
    const names = new Set(cases.map((c) => c.name));
    for (const required of [
      'sentences_no_trailing_whitespace',
      'headings_empty_and_duplicate',
      'headings_cap_200_after_empty_skip',
      'links_non_http_schemes',
      'links_subdomain_vs_same_host',
      'zero_text_page',
      'flesch_clamp_single_sentence',
      'missing_title_description_canonical',
    ]) {
      expect(names, `fixture lost coverage for ${required}`).toContain(required);
    }
  });

  it('compares every field the generator says it compares', () => {
    const declared = (fixture as { compared_fields: string[] }).compared_fields;
    const first = cases[0];
    expect(first).toBeDefined();
    // The generator and this test must agree on the surface under comparison.
    // If the Python starts emitting a new comparable field, this fails rather
    // than letting the new field drift uncovered.
    expect(Object.keys((first as ParityCase).expected).sort()).toEqual([...declared].sort());
  });

  it('leaves only the browser-only fields uncompared', () => {
    const actual = runAudit(parse('<html><body></body></html>'), 'https://example.com/page');
    const compared = new Set(Object.keys(toServerShape(actual)));
    // Every SeoAudit key is either compared (under its own or its display name)
    // or listed in UNCOMPARED_BY_DESIGN above with a stated reason.
    const displayAliases = new Set([
      'title',
      'description',
      'links',
      'images',
      ...UNCOMPARED_BY_DESIGN,
    ]);
    for (const key of Object.keys(actual)) {
      expect(
        compared.has(key) || displayAliases.has(key),
        `SeoAudit.${key} is neither compared nor explicitly skipped`,
      ).toBe(true);
    }
  });

  for (const c of cases) {
    it(`${c.name} — ${c.why}`, () => {
      expect(toServerShape(runAudit(parse(c.html), c.base_url))).toEqual(c.expected);
    });
  }
});
